version: "3"
services:
  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-db
    networks:
      - mern-stack-net
    volumes:
      - mongo-data:/data/db
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    container_name: mern-backend
    networks:
      - mern-stack-net
    volumes:
      - ./backend:/usr/app
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    container_name: mern-frontend
    networks:
      - mern-stack-net
    volumes:
      - ./frontend/src:/usr/app/src
      - ./frontend/public:/usr/app/public
    depends_on:
      - backend
    stdin_open: true
    tty: true

networks:
  mern-stack-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local
